config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :players
  resource :session
end

app/models/player.rb
class Player < ActiveRecord::Base

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(player_params)
    player = Player.find_by_playername(player_params[:playername])
    player.try(:is_password?, player_params[:password]) ? player : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def is_admin?
    playername == "oreosleeve"
  end

  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_player, :signed_in?

  private

  def current_player
    return nil unless session[:token]
    @current_player ||= Player.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_player
  end

  def is_admin?
  end

  def sign_in!(player)
    @current_player = player
    session[:token] = player.reset_token!
  end

  def sign_out!
    current_player.try(:reset_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new; end

  def create
    @player = player_params ? Player.new(player_params) : Player.new_guest
    if @player.save
      current_player.move_to(@player) if current_player
      session[:player_id] = @player.id
      redirect_to player_url(@player)
    else
      render "show"
    end
  end

  def show
    @player = Player.find(params[:id])
    render :show
  end

  private

  def player_params
    params.require(:player).permit(:playername, :password, :session_token)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @player = Player.find_by_credentials(params[:player])

    if @player
      sign_in!(@player)
      redirect_to player_url(@player)
    else
      flash.now[:errors] = ["Invalid player name and/or password"]
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-bottom">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">footer stuff</a>
    </div>
    <div>
      <ul class="nav navbar-nav header-list">
        <li><a class="navbar-brand" href="#">About</a></li>
        <li><a class="navbar-brand" href="#">Tourney Rules</a></li>
        <li><a class="navbar-brand" href="#">Prizes</a></li>
        <li><a class="navbar-brand" href="#">Hosting</a></li>
        <li><a class="navbar-brand" href="#">Organizers and Helpers</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Tournament name</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav header-list">
      <li><a class="navbar-brand glyphicon glyphicon-home" href="#"></a></li>
      <li><a class="navbar-brand" href="#">Players Link</a></li>
      <li><a class="navbar-brand" href="#">Tee Times Link</a></li>
      <li><a class="navbar-brand" href="#">Leaderboard Link</a></li>
    </ul>
    <% if signed_in? %>
      <div class='sign-out'>
        <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %></li>
      </div>
    <% else %>
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_player_url %></li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GolfTournament</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
</body>
</html>

app/views/players/new.html.erb
<h1>Sign Up</h1>

<form action="/players" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Player name<br>
    <input name="player[playername]" type="text"><br>
  </label><br>
  <label>Password<br>
    <input name="player[password]" type="password"><br>
  </label><br>
  <input type="submit" value="Submit" class="btn btn-primary"><br>
</form>

app/views/players/show.html.erb
Hey <%= @player.playername%>. Nothing here to show yet. Just getting started. Cheers.
You are
<% if @player.is_admin? %>
  an admin! hooray!
<% else %>
 not an admin :( sorry
 <%end%>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <div id="main"></div>
</div>
<script>$(GolfTournament.initialize);
</script>